name: CD - Semantic Release

on:
  workflow_call:
    inputs:
      stack:
        description: 'Stack the project. (node | php | dotnet | python | go | empty for auto-detect)'
        required: false
        type: string
        default: null
      project_path:
        description: 'Project path source code'
        required: false
        type: string
        default: null

      semantic_release_config:
        description: 'Path to semantic-release config file.'
        required: false
        type: string
      semantic_release_dry_run:
        description: 'Dry run mode for semantic-release. (default: false -> true for PRs)'
        required: false
        type: boolean
        default: false
      semantic_release_debug_mode:
        description: 'Debug mode for semantic-release.'
        required: false
        type: boolean
        default: false
      strict_conventional_commits:
        description: 'Fail pipeline if no conventional commits are found'
        required: false
        type: boolean
        default: true

    secrets:
      GH_TOKEN:
        required: true

jobs:
  semantic-release:
    runs-on: ubuntu-latest
    env:
      REUSABLE_PATH: ${{ github.workspace }}/${{ inputs.project_path }}/__reusable_actions__
      BASH_ENV: ${{ github.workspace }}/${{ inputs.project_path }}/__reusable_actions__/scripts/shared/shell-helpers.sh

    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.project_path || '.' }}

    permissions:
      actions: read
      contents: write
      issues: write
      pull-requests: write

    steps:
      - name: 📌 Checkout consumer repository
        uses: actions/checkout@v4
        with: 
          # A linha 'ref: ${{ github.event.workflow_run.head_sha }}
          fetch-depth: 0 	  # Necessário para o semantic-release inspecionar histórico
          fetch-tags: true 	# Necessário para o semantic-release inspecionar tags
          persist-credentials: true  # → permite push com GITHUB_TOKEN
          token: ${{ secrets.GH_TOKEN }} # Necessário para autenticar PUSH

      - name: 📌 Checkout reusable-actions scripts
        uses: actions/checkout@v4
        with:
          repository: heliomarpm/reusable-actions
          ref: main
          path: ${{ env.REUSABLE_PATH }}
          token: ${{ secrets.GH_TOKEN }} # Necessário se o repositório for privado

      - name: 👀 Files in workspace
        run: |
          ls_files

      - name: 🔍 Resolve project stack
        id: stack
        run: |
          STACK="${{ inputs.stack }}"
          if [[ -n "$STACK" ]]; then
            echo "🔹 Using stack from input: $STACK"
            echo "value=$STACK" >> $GITHUB_OUTPUT
            echo "source=input" >> $GITHUB_OUTPUT
            exit 0
          fi

          SCRIPT="$REUSABLE_PATH/scripts/shared/detect-stack.sh"
          chmod +x "$SCRIPT"
          STACK=$("$SCRIPT")

          if [[ -z "$STACK" ]]; then
            echo "value=" >> $GITHUB_OUTPUT
            echo "source=not-detected" >> $GITHUB_OUTPUT
            exit 0
          fi

          echo "✅ Detected stack: $STACK"
          echo "value=$STACK" >> $GITHUB_OUTPUT
          echo "source=detected" >> $GITHUB_OUTPUT
          
      - name: ❌ Fail if stack not detected
        if: steps.stack.outputs.value == ''
        run: |
          fail "Stack not detected. Check project_path or repository structure."          

      - name: ⚙️ Configurar Usuário Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: 🚀 Run Release
        if: steps.stack.outputs.value != ''
        run: |
          SCRIPT="$REUSABLE_PATH/scripts/shared/semantic-release/run.sh"
          chmod +x "$SCRIPT"
          "$SCRIPT"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          STACK: ${{ steps.stack.outputs.value }}
          REUSABLE_PATH: ${{ env.REUSABLE_PATH }}
          SEMANTIC_RELEASE_CONFIG: ${{ inputs.semantic_release_config }}
          SEMANTIC_RELEASE_DRY_RUN: ${{ inputs.semantic_release_dry_run }}
          SEMANTIC_RELEASE_DEBUG_MODE: ${{ inputs.semantic_release_debug_mode }}
          STRICT_CONVENTIONAL_COMMITS: ${{ inputs.strict_conventional_commits }}

      - name: 🧾 Job Summary
        if: always()
        run: |
          {
            echo "## 📌 Semantic Release"
            echo ""
            echo "**📂 Project path:** \`${{ inputs.project_path }}\`"
            echo ""

            if [[ "${{ steps.stack.outputs.value }}" != "" ]]; then
              echo "**🧱 Stack:** \`${{ steps.stack.outputs.value }}\` (_${{ steps.stack.outputs.source }}_)"
            else
              echo "**🧱 Stack:** ❌ not detected"
            fi

          } >> $GITHUB_STEP_SUMMARY
