name: "Changelog Generator"

on:
  workflow_dispatch:
    inputs:
      version-format:
        description: 'Formato da versão (ex: "v%major.%minor.%patch" ou "%YYYY-%mm-%dd")'
        type: string
        default: ''

  push:
    branches:
      - main
      - develop
    paths-ignore:
      - 'CHANGELOG.md'

jobs:
  changelog:
    name: 📝 Changelog Generator
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: 📌 Checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: 🚀 Run Changelog Action
        uses: ./actions/changelog
        # with:
        #   branch: ${{ github.ref_name }}
        #   create-release: ${{ (github.event_name == 'workflow_dispatch' && inputs.create-release) || github.ref_name == 'main' }}
        #   github-token: ${{ secrets.GITHUB_TOKEN }}