name: CI - Quality Gate

on:
  workflow_call:
    inputs:
      stack:
        description: 'Stack the project. (node | php | dotnet | python | go | empty for auto-detect)'
        required: false
        type: string
        default: null     # node | php | dotnet | python | go | empty for auto-detect
      project_path:
        required: false
        type: string
        default: "."
      source_private:
        description: 'Source repository is private. GH_TOKEN will be required if the repository is private.'
        required: false
        type: boolean
        default: false

      min-coverage:
        description: 'Minimum coverage percentage (0-100 | default: 80)'
        type: number
        required: false
        default: 80
      coverage-mode:
        description: 'Coverage mode (info | block | decrease-only)'
        type: string
        required: false
        default: "info" 

      coverage_continue_on_failure:
        description: 'Continue pipeline even if tests fail. (default: true)'
        required: false
        type: boolean
        default: true

  secrets:
    GH_TOKEN:
      required: false

jobs:
  qualitys: 
    runs-on: ubuntu-latest
    env:
      REUSABLE_PATH: __reusable_actions__
      BASH_ENV: __reusable_actions__/scripts/shared/shell-helpers.sh

    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.project_path }}

    permissions:
      contents: read
      actions: read

    steps:
      - name: 📌 Checkout consumer repository (private)
        if: ${{ inputs.source_private }}
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }} 

      - name: 📌 Checkout consumer repository
        if: ${{ inputs.source_private == false }}
        uses: actions/checkout@v4

      - name: 📌 Checkout reusable-actions scripts
        uses: actions/checkout@v4
        with:
          repository: heliomarpm/reusable-actions
          ref: main
          path: ${{ env.REUSABLE_PATH }}

      - name: 👀 Files in workspace
        run: |
          ls_files

      - name: 🔍 Resolve project stack
        id: stack
        # working-directory: ${{ inputs.project_path }}
        run: |
          STACK="${{ inputs.stack }}"
          if [[ -n "$STACK" ]]; then
            echo "🔹 Using stack from input: $STACK"
            echo "value=$STACK" >> $GITHUB_OUTPUT
            echo "source=input" >> $GITHUB_OUTPUT
            exit 0
          fi
            
          SCRIPT="$REUSABLE_PATH/scripts/shared/detect-stack.sh"
          chmod +x "$SCRIPT"
          STACK=$("$SCRIPT")
          
          if [[ -z "$STACK" ]]; then
            echo "value=" >> $GITHUB_OUTPUT
            echo "source=not-detected" >> $GITHUB_OUTPUT
            exit 0
          fi

          echo "✅ Detected stack: $STACK"
          echo "value=$STACK" >> $GITHUB_OUTPUT
          echo "source=detected" >> $GITHUB_OUTPUT

      - name: ❌ Fail if stack not detected
        if: steps.stack.outputs.value == ''
        run: |
          fail "Stack not detected. Check project_path or repository structure."          

      - name: 🧪 Evaluate test execution
        id: tests
        # working-directory: ${{ inputs.project_path }}
        run: |
          if [[ ! -d "tests" && ! -d "__tests__" && ! -d "test" ]]; then
            echo "skip=false" >> $GITHUB_OUTPUT
            echo "reason=no test folders detected" >> $GITHUB_OUTPUT
            fail "No test directories found."
          fi

          echo "✅ Tests will run."
          echo "reason=tests detected" >> $GITHUB_OUTPUT
  
      - name: ▶️ Run unit tests
        # working-directory: ${{ inputs.project_path }}
        run: |
          STACK="${{ steps.stack.outputs.value }}"
          SCRIPT="$REUSABLE_PATH/scripts/plugins/$STACK/test.sh"
          chmod +x "$SCRIPT"
          "$SCRIPT"

      - name: 📊 Run coverage tests
        id: coverage
        # working-directory: ${{ inputs.project_path }}
        continue-on-error: ${{ inputs.coverage_continue_on_failure }}
        run: |
          STACK="${{ steps.stack.outputs.value }}"
          SCRIPT="$REUSABLE_PATH/scripts/plugins/$STACK/coverage.sh"
          chmod +x "$SCRIPT"
          # "$SCRIPT"

          if "$SCRIPT"; then
            STATUS="executed"
          else
            STATUS="failed"
          fi
          echo "status=$STATUS" >> $GITHUB_OUTPUT

          FILE="coverage/coverage-summary.normalized.json"

          if [[ -f "$FILE" ]]; then
            LINE=$(jq '.line' "$FILE")
            echo "line=$LINE" >> $GITHUB_OUTPUT

            PCT=$(jq -r '.total.lines.pct // empty' "$FILE")
            if [[ -n "$PCT" ]]; then
              echo "pct=$PCT" >> $GITHUB_OUTPUT
            fi

            echo "report=found" >> $GITHUB_OUTPUT
          else
            echo "line=" >> $GITHUB_OUTPUT
            echo "report=not-found" >> $GITHUB_OUTPUT
          fi

      - name: ✅ Evaluate coverage
        id: coverage-check
        run: |
          REPORT_STATUS="${{ steps.coverage.outputs.report }}"
          LINE=${{ steps.coverage.outputs.line }}
          MIN=${{ inputs.min-coverage }}
          MODE="${{ inputs.coverage-mode }}"

          log "Minimum coverage: $MIN%"
          log "Coverage mode: $MODE"

          FINAL_STATUS="passed"

          if [ "$REPORT_STATUS" = "not-found" ]; then
            FINAL_STATUS="missing"
            echo "⚠️ No tests or coverage detected"

            if [ "$MODE" = "block" ]; then
              fail "Blocking PR: tests not implemented"
            fi
          elif  (( $(echo "$LINE < $MIN" | bc -l) )); then
            FINAL_STATUS="failed"
            MSG="❌ Coverage below threshold ($LINE < $MIN)"

            if [ "$MODE" = "block" ]; then
              fail "$MSG"
              exit 1
            fi

            echo "$MSG"
          fi

          echo "status=$FINAL_STATUS" >> $GITHUB_OUTPUT

      - name: 📦 Upload coverage artifact
        # if: hashFiles('coverage/coverage-summary.normalized.json') != ''
        if: steps.coverage.outputs.report != 'not-found'
        uses: actions/upload-artifact@v4
        continue-on-error: true
        with:
          name: coverage-report
          path: coverage/coverage-summary.normalized.json

      - name: 🧾 Job Summary
        if: always()
        run: |
          {
            echo "## 🧪 Quality Gate "
            echo ""
            echo "**📂 Project path:** \`${{ inputs.project_path }}\`"
            echo ""

            if [[ "${{ steps.stack.outputs.value }}" != "" ]]; then
              echo "**🧱 Stack:** \`${{ steps.stack.outputs.value }}\` (_${{ steps.stack.outputs.source }}_)"
            else
              echo "**🧱 Stack:** ❌ not detected"
            fi

            echo ""
            if [[ "${{ steps.tests.outputs.skip }}" != "true" ]]; then
              echo "**🧪 Tests:** executed"
            else
              echo "**🧪 Tests:** skipped (_${{ steps.tests.outputs.reason }}_)"
            fi

            echo ""
            if [[ "${{ steps.coverage.outputs.status }}" == "executed" ]]; then
              if [[ -n "${{ steps.coverage.outputs.pct }}" ]]; then
                echo "**📊 Coverage:** ${{ steps.coverage.outputs.pct }}%"
              else
                echo "**📊 Coverage:** executed (no summary produced)"
              fi
            elif [[ "${{ steps.coverage.outputs.status }}" == "failed" ]]; then
              echo "**📊 Coverage:** failed"
            else
              echo "**📊 Coverage:** not executed"
            fi

            echo ""
            if [[ -f coverage/coverage-summary.normalized.json ]]; then
              echo "**📦 Artifacts:** coverage-report"
            fi
          } >> $GITHUB_STEP_SUMMARY
